import type { Metadata } from "next";
import "./globals.css";
import Outlet from "./outlet";


export const metadata: Metadata = {
  title: "TODO with UseContext API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Outlet>{children}</Outlet>
      </body>
    </html>
  );
}
